unit UJConsts;

interface

const
  CELL_IMG_IDX_SHIP_RED = 0;
  CELL_IMG_IDX_SHIP_BLACK = 1;
  CELL_IMG_IDX_SHIP_YELLOW = 2;
  CELL_IMG_IDX_SHIP_WHITE = 3;
  CELL_IMG_IDX_LAND = 4;
  CELL_IMG_IDX_EMPTY1 = 5;
  CELL_IMG_IDX_EMPTY2 = 6;
  CELL_IMG_IDX_EMPTY3 = 7;
  CELL_IMG_IDX_EMPTY4 = 8;
  CELL_IMG_IDX_DOUBLE_MOVE = 9;
  CELL_IMG_IDX_ONE_ARROW_PLAIN = 10;
  CELL_IMG_IDX_ONE_ARROW_DIAGONAL = 11;
  CELL_IMG_IDX_TWO_ARROWS_PLAIN = 12;
  CELL_IMG_IDX_TWO_ARROWS_DIAGONAL = 13;
  CELL_IMG_IDX_THREE_ARROWS = 14;
  CELL_IMG_IDX_FOUR_ARROWS_PLAIN = 15;
  CELL_IMG_IDX_FOUR_ARROWS_DIAGONAL = 16;
  CELL_IMG_IDX_TRAP = 17;

implementation

end.
